import { Link } from "@tanstack/react-router";
import { Activity, ArrowRight, BadgeCheck, CircleDollarSign, Clock3, FileSearch, PackageCheck, TrendingUp, Users } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { MetricCard, PageHeader, StatusBadge } from "@/components/procurement-ui";
import { approvals, formatBDT, tenders } from "@/lib/procurement";

const pipeline = [{ label: "Requests", value: 42 }, { label: "Review", value: 18 }, { label: "Tendering", value: 14 }, { label: "Evaluation", value: 7 }, { label: "Awarded", value: 11 }, { label: "Delivery", value: 16 }];
const activity = [
  ["OTM-2026-0042 published", "Dignity kits tender opened to suppliers", "12 minutes ago"],
  ["PO-2026-0216 approved", "Approved by Finance Director", "38 minutes ago"],
  ["GRN-2026-0148 recorded", "Medical consumables received at Dhaka warehouse", "2 hours ago"],
  ["RFP-2026-0019 evaluated", "Technical evaluation completed by committee", "Yesterday"],
];

export function Dashboard() {
  const [approved, setApproved] = useState<string[]>([]);
  return <div className="space-y-7"><PageHeader title="Good afternoon, Nabila" description="Here is today’s procurement position across Bangladesh programmes." action={<Button asChild><Link to="/requisitions"><span>New requisition</span><ArrowRight className="size-4" /></Link></Button>} />
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Procurement overview"><MetricCard label="FY procurement spend" value="৳ 18.42 Cr" detail="68% of approved annual plan" icon={<CircleDollarSign className="size-5" />} /><MetricCard label="Pending approvals" value="7" detail="2 require action today" icon={<BadgeCheck className="size-5" />} /><MetricCard label="Active tenders" value="14" detail="3 close within 7 days" icon={<FileSearch className="size-5" />} /><MetricCard label="On-time delivery" value="91.6%" detail="Up 3.2% from last quarter" icon={<TrendingUp className="size-5" />} /></section>
    <section className="grid gap-6 xl:grid-cols-[minmax(0,1.5fr)_minmax(300px,0.8fr)]"><div className="rounded-md border border-border bg-card shadow-card"><div className="flex items-center justify-between border-b border-border px-5 py-4"><div><h2 className="font-bold text-foreground">Pending your approval</h2><p className="mt-0.5 text-xs text-muted-foreground">Items ordered by urgency and due date</p></div><Link to="/approvals" className="text-sm font-semibold text-primary hover:underline">View all</Link></div><div className="divide-y divide-border">{approvals.slice(0, 3).map((item) => <article key={item.id} className="p-5"><div className="grid grid-cols-[minmax(0,1fr)_auto] gap-3"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-bold text-primary">{item.id}</span><StatusBadge tone={approved.includes(item.id) ? "success" : item.tone}>{approved.includes(item.id) ? "Approved" : item.status}</StatusBadge></div><h3 className="mt-2 truncate text-sm font-semibold text-foreground">{item.title}</h3><p className="mt-1 text-xs text-muted-foreground">{item.department} · {item.owner}</p></div><div className="text-right"><p className="text-sm font-bold text-foreground">{formatBDT(item.value)}</p><p className="mt-1 text-xs text-muted-foreground">Due {item.date}</p></div></div>{!approved.includes(item.id) && <div className="mt-4 flex gap-2"><Button size="sm" onClick={() => setApproved((items) => [...items, item.id])}>Approve</Button><Button size="sm" variant="secondary">Review</Button></div>}</article>)}</div></div>
      <div className="rounded-md border border-border bg-card p-5 shadow-card"><div className="flex items-center justify-between"><h2 className="font-bold text-foreground">Annual plan</h2><span className="text-xs font-semibold text-muted-foreground">FY 2026–27</span></div><div className="mt-5"><div className="flex items-end justify-between"><p className="text-3xl font-bold">68%</p><p className="text-xs text-muted-foreground">৳18.42 Cr of ৳27.10 Cr</p></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full w-[68%] rounded-full bg-primary" /></div></div><dl className="mt-7 space-y-4 text-sm"><div className="flex justify-between"><dt className="text-muted-foreground">Committed</dt><dd className="font-semibold">৳4.62 Cr</dd></div><div className="flex justify-between"><dt className="text-muted-foreground">Available</dt><dd className="font-semibold text-success">৳4.06 Cr</dd></div><div className="flex justify-between"><dt className="text-muted-foreground">Forecast saving</dt><dd className="font-semibold">৳0.78 Cr</dd></div></dl><Link to="/plans" className="mt-6 inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-primary">Open procurement plan <ArrowRight className="size-4" /></Link></div></section>
    <section className="grid gap-6 xl:grid-cols-[minmax(0,1.4fr)_minmax(300px,0.9fr)]"><div className="rounded-md border border-border bg-card p-5 shadow-card"><div className="flex items-center justify-between"><div><h2 className="font-bold">Procurement pipeline</h2><p className="mt-0.5 text-xs text-muted-foreground">108 active activities across all stages</p></div><Activity className="size-5 text-muted-foreground" /></div><div className="mt-8 grid grid-cols-3 gap-5 sm:grid-cols-6">{pipeline.map((step, i) => <div key={step.label} className="relative text-center"><div className="mx-auto grid size-11 place-items-center rounded-full border-4 border-accent bg-primary text-sm font-bold text-primary-foreground">{step.value}</div>{i < pipeline.length - 1 && <span className="absolute left-[65%] top-5 hidden h-px w-[70%] bg-border sm:block" />}<p className="mt-2 text-xs font-medium text-muted-foreground">{step.label}</p></div>)}</div></div><div className="rounded-md border border-border bg-card shadow-card"><div className="border-b border-border px-5 py-4"><h2 className="font-bold">Recent activity</h2></div><ul className="divide-y divide-border">{activity.map(([title, detail, time]) => <li key={title} className="flex gap-3 px-5 py-3"><div className="mt-1 grid size-7 shrink-0 place-items-center rounded-full bg-accent text-primary"><Clock3 className="size-3.5" /></div><div className="min-w-0"><p className="text-sm font-semibold">{title}</p><p className="mt-0.5 truncate text-xs text-muted-foreground">{detail}</p><p className="mt-1 text-[11px] text-muted-foreground">{time}</p></div></li>)}</ul></div></section>
    <section className="grid gap-4 sm:grid-cols-3"><Link to="/suppliers" className="flex min-h-24 items-center gap-4 rounded-md border border-border bg-card p-5 shadow-card hover:border-primary"><Users className="size-8 text-primary" /><div><p className="text-xl font-bold">247</p><p className="text-sm text-muted-foreground">Registered suppliers</p></div></Link><Link to="/receiving" className="flex min-h-24 items-center gap-4 rounded-md border border-border bg-card p-5 shadow-card hover:border-primary"><PackageCheck className="size-8 text-primary" /><div><p className="text-xl font-bold">16</p><p className="text-sm text-muted-foreground">Deliveries in progress</p></div></Link><Link to="/tenders" className="flex min-h-24 items-center gap-4 rounded-md border border-border bg-card p-5 shadow-card hover:border-primary"><FileSearch className="size-8 text-primary" /><div><p className="text-xl font-bold">3</p><p className="text-sm text-muted-foreground">Deadlines this week</p></div></Link></section>
  </div>;
}