import { Plus } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { PageHeader, RecordsTable } from "@/components/procurement-ui";
import { moduleDefinitions, moduleRecords, type ProcurementRecord } from "@/lib/procurement";

export function ModulePage({ module }: { module: keyof typeof moduleDefinitions }) {
  const definition = moduleDefinitions[module];
  const records = moduleRecords[module] ?? [];
  const [selected, setSelected] = useState<ProcurementRecord>();
  const [showCreate, setShowCreate] = useState(false);
  if (!definition) return null;
  return <div className="space-y-6"><PageHeader title={definition.title} description={definition.description} action={<Button onClick={() => setShowCreate(true)}><Plus className="size-4" />{definition.action}</Button>} /><RecordsTable records={records} emptyLabel={definition.title.toLowerCase()} onOpen={setSelected} />{(selected || showCreate) && <div className="fixed inset-0 z-50 grid place-items-end bg-overlay p-0 sm:place-items-center sm:p-4" role="presentation" onMouseDown={(e) => e.target === e.currentTarget && (setSelected(undefined), setShowCreate(false))}><section role="dialog" aria-modal="true" aria-labelledby="modal-title" className="max-h-[90dvh] w-full overflow-y-auto rounded-t-lg bg-card p-6 shadow-dialog sm:max-w-lg sm:rounded-lg"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase text-primary">{selected?.id ?? `New ${definition.singular}`}</p><h2 id="modal-title" className="mt-1 text-xl font-bold text-foreground">{selected?.title ?? definition.action}</h2></div><Button variant="ghost" size="icon" aria-label="Close dialog" onClick={() => { setSelected(undefined); setShowCreate(false); }}><span aria-hidden="true">×</span></Button></div>{selected ? <dl className="mt-6 grid grid-cols-2 gap-5 text-sm"><div><dt className="text-muted-foreground">Department</dt><dd className="mt-1 font-semibold">{selected.department}</dd></div><div><dt className="text-muted-foreground">Status</dt><dd className="mt-1 font-semibold">{selected.status}</dd></div><div><dt className="text-muted-foreground">Responsible</dt><dd className="mt-1 font-semibold">{selected.owner}</dd></div><div><dt className="text-muted-foreground">Updated / due</dt><dd className="mt-1 font-semibold">{selected.date}</dd></div></dl> : <form className="mt-6 space-y-4" onSubmit={(e) => { e.preventDefault(); setShowCreate(false); }}><label className="block text-sm font-semibold">Title <span className="text-destructive">*</span><input required className="mt-2 h-11 w-full rounded-md border border-input bg-background px-3 font-normal outline-none focus:ring-2 focus:ring-ring" /></label><label className="block text-sm font-semibold">Department <span className="text-destructive">*</span><select required className="mt-2 h-11 w-full rounded-md border border-input bg-background px-3 font-normal"><option>Humanitarian Response</option><option>Health Programme</option><option>Operations</option></select></label><label className="block text-sm font-semibold">Estimated value (BDT)<input type="number" min="0" className="mt-2 h-11 w-full rounded-md border border-input bg-background px-3 font-normal outline-none focus:ring-2 focus:ring-ring" /></label><div className="flex justify-end gap-2 pt-2"><Button type="button" variant="secondary" onClick={() => setShowCreate(false)}>Cancel</Button><Button type="submit">Save draft</Button></div></form>}</section></div>}</div>;
}