/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as EvaluationsRouteImport } from './routes/evaluations'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as PurchaseOrdersRouteImport } from './routes/purchase-orders'
import { Route as ReceivingRouteImport } from './routes/receiving'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RequisitionsRouteImport } from './routes/requisitions'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as SurveysRouteImport } from './routes/surveys'
import { Route as TendersRouteImport } from './routes/tenders'
import { Route as VendorIndexRouteImport } from './routes/vendor/index'
import { Route as VendorBidsRouteImport } from './routes/vendor/bids'
import { Route as VendorOrdersRouteImport } from './routes/vendor/orders'
import { Route as VendorTendersRouteImport } from './routes/vendor/tenders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationsRoute = EvaluationsRouteImport.update({
  id: '/evaluations',
  path: '/evaluations',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersRoute = PurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceivingRoute = ReceivingRouteImport.update({
  id: '/receiving',
  path: '/receiving',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RequisitionsRoute = RequisitionsRouteImport.update({
  id: '/requisitions',
  path: '/requisitions',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveysRoute = SurveysRouteImport.update({
  id: '/surveys',
  path: '/surveys',
  getParentRoute: () => rootRouteImport,
} as any)
const TendersRoute = TendersRouteImport.update({
  id: '/tenders',
  path: '/tenders',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorIndexRoute = VendorIndexRouteImport.update({
  id: '/vendor/',
  path: '/vendor/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorBidsRoute = VendorBidsRouteImport.update({
  id: '/vendor/bids',
  path: '/vendor/bids',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorOrdersRoute = VendorOrdersRouteImport.update({
  id: '/vendor/orders',
  path: '/vendor/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorTendersRoute = VendorTendersRouteImport.update({
  id: '/vendor/tenders',
  path: '/vendor/tenders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/contracts': typeof ContractsRoute
  '/evaluations': typeof EvaluationsRoute
  '/inventory': typeof InventoryRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/plans': typeof PlansRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/receiving': typeof ReceivingRoute
  '/reports': typeof ReportsRoute
  '/requisitions': typeof RequisitionsRoute
  '/suppliers': typeof SuppliersRoute
  '/surveys': typeof SurveysRoute
  '/tenders': typeof TendersRoute
  '/vendor/bids': typeof VendorBidsRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/tenders': typeof VendorTendersRoute
  '/vendor/': typeof VendorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/contracts': typeof ContractsRoute
  '/evaluations': typeof EvaluationsRoute
  '/inventory': typeof InventoryRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/plans': typeof PlansRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/receiving': typeof ReceivingRoute
  '/reports': typeof ReportsRoute
  '/requisitions': typeof RequisitionsRoute
  '/suppliers': typeof SuppliersRoute
  '/surveys': typeof SurveysRoute
  '/tenders': typeof TendersRoute
  '/vendor/bids': typeof VendorBidsRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/tenders': typeof VendorTendersRoute
  '/vendor': typeof VendorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/contracts': typeof ContractsRoute
  '/evaluations': typeof EvaluationsRoute
  '/inventory': typeof InventoryRoute
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/plans': typeof PlansRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/receiving': typeof ReceivingRoute
  '/reports': typeof ReportsRoute
  '/requisitions': typeof RequisitionsRoute
  '/suppliers': typeof SuppliersRoute
  '/surveys': typeof SurveysRoute
  '/tenders': typeof TendersRoute
  '/vendor/bids': typeof VendorBidsRoute
  '/vendor/orders': typeof VendorOrdersRoute
  '/vendor/tenders': typeof VendorTendersRoute
  '/vendor/': typeof VendorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/audit'
    | '/contracts'
    | '/evaluations'
    | '/inventory'
    | '/notifications'
    | '/payments'
    | '/plans'
    | '/purchase-orders'
    | '/receiving'
    | '/reports'
    | '/requisitions'
    | '/suppliers'
    | '/surveys'
    | '/tenders'
    | '/vendor/bids'
    | '/vendor/orders'
    | '/vendor/tenders'
    | '/vendor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/audit'
    | '/contracts'
    | '/evaluations'
    | '/inventory'
    | '/notifications'
    | '/payments'
    | '/plans'
    | '/purchase-orders'
    | '/receiving'
    | '/reports'
    | '/requisitions'
    | '/suppliers'
    | '/surveys'
    | '/tenders'
    | '/vendor/bids'
    | '/vendor/orders'
    | '/vendor/tenders'
    | '/vendor'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/audit'
    | '/contracts'
    | '/evaluations'
    | '/inventory'
    | '/notifications'
    | '/payments'
    | '/plans'
    | '/purchase-orders'
    | '/receiving'
    | '/reports'
    | '/requisitions'
    | '/suppliers'
    | '/surveys'
    | '/tenders'
    | '/vendor/bids'
    | '/vendor/orders'
    | '/vendor/tenders'
    | '/vendor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AuditRoute: typeof AuditRoute
  ContractsRoute: typeof ContractsRoute
  EvaluationsRoute: typeof EvaluationsRoute
  InventoryRoute: typeof InventoryRoute
  NotificationsRoute: typeof NotificationsRoute
  PaymentsRoute: typeof PaymentsRoute
  PlansRoute: typeof PlansRoute
  PurchaseOrdersRoute: typeof PurchaseOrdersRoute
  ReceivingRoute: typeof ReceivingRoute
  ReportsRoute: typeof ReportsRoute
  RequisitionsRoute: typeof RequisitionsRoute
  SuppliersRoute: typeof SuppliersRoute
  SurveysRoute: typeof SurveysRoute
  TendersRoute: typeof TendersRoute
  VendorBidsRoute: typeof VendorBidsRoute
  VendorOrdersRoute: typeof VendorOrdersRoute
  VendorTendersRoute: typeof VendorTendersRoute
  VendorIndexRoute: typeof VendorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluations': {
      id: '/evaluations'
      path: '/evaluations'
      fullPath: '/evaluations'
      preLoaderRoute: typeof EvaluationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders': {
      id: '/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof PurchaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receiving': {
      id: '/receiving'
      path: '/receiving'
      fullPath: '/receiving'
      preLoaderRoute: typeof ReceivingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requisitions': {
      id: '/requisitions'
      path: '/requisitions'
      fullPath: '/requisitions'
      preLoaderRoute: typeof RequisitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveys': {
      id: '/surveys'
      path: '/surveys'
      fullPath: '/surveys'
      preLoaderRoute: typeof SurveysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenders': {
      id: '/tenders'
      path: '/tenders'
      fullPath: '/tenders'
      preLoaderRoute: typeof TendersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/': {
      id: '/vendor/'
      path: '/vendor'
      fullPath: '/vendor/'
      preLoaderRoute: typeof VendorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/bids': {
      id: '/vendor/bids'
      path: '/vendor/bids'
      fullPath: '/vendor/bids'
      preLoaderRoute: typeof VendorBidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/orders': {
      id: '/vendor/orders'
      path: '/vendor/orders'
      fullPath: '/vendor/orders'
      preLoaderRoute: typeof VendorOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/tenders': {
      id: '/vendor/tenders'
      path: '/vendor/tenders'
      fullPath: '/vendor/tenders'
      preLoaderRoute: typeof VendorTendersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  AuditRoute: AuditRoute,
  ContractsRoute: ContractsRoute,
  EvaluationsRoute: EvaluationsRoute,
  InventoryRoute: InventoryRoute,
  NotificationsRoute: NotificationsRoute,
  PaymentsRoute: PaymentsRoute,
  PlansRoute: PlansRoute,
  PurchaseOrdersRoute: PurchaseOrdersRoute,
  ReceivingRoute: ReceivingRoute,
  ReportsRoute: ReportsRoute,
  RequisitionsRoute: RequisitionsRoute,
  SuppliersRoute: SuppliersRoute,
  SurveysRoute: SurveysRoute,
  TendersRoute: TendersRoute,
  VendorBidsRoute: VendorBidsRoute,
  VendorOrdersRoute: VendorOrdersRoute,
  VendorTendersRoute: VendorTendersRoute,
  VendorIndexRoute: VendorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
